### PR TITLE
Use codecov v4, single upload step, and non-codecov reports

### PR DESCRIPTION
**Pull request by Czaki**
This PR solves https://github.com/napari/napari-graph/pull/13#issuecomment-2141196170 and moves coverage upload to a separate step to make the CI logs cleaner.

It also adds support for GHA-only coverage reports using the method from
[hynek.me/articles/ditch-codecov-python](https://hynek.me/articles/ditch-codecov-python/)

### CODE REVIEW

**Comment by jni** [comment]
Nice! Thanks @Czaki! However it is currently failing in a weird way. 😅

**Comment by Czaki** [comment]
> Nice! Thanks @Czaki! However it is currently failing in a weird way. 😅

It is not verid. I hit this every time I migrate to this schema. it is only problem with paths between operating systems...

**Comment by Czaki** [comment]
@jni it is ready to review. 
Also contains [hynek.me/articles/ditch-codecov-python](https://hynek.me/articles/ditch-codecov-python/)

obraz

It looks like branch coverage is handled differently on codecov.io and normal report.

**Review by jni — APPROVED** [review]

**Comment by jni** [comment]
Amazing! Thank you @Czaki!

**Pull request merged**
